version: '3.8'
services:
  movies:
    image: alexlaxu/paytmmoviesrepo:latest
    ports:
      - '81:80'
    deploy:
      replicas: 3

  train:
    image: alexlaxu/paytmtrainrepo:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  dth:
    image: alexlaxu/paytmdthrepo:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  recharge:
    image: alexlaxu/paytmrechargerepo:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3
